### ISSUE TITLE
在 vercel 部署后丢失了 css 样式，请教如何正确部署？

### ISSUE THREAD

**Issue by chilohwei** [tw93/tw93.github.io#147]
首先感谢 tw93 的开源，在推特上也有关注您。这个博客风格很简约，我非常喜欢。在本地尝试部署调试，没有遇到任何问题，一切正常。

但当我在 Vercel 上部署时，似乎丢失了页面 css 样式，如下图：

![image](https://github.com/tw93/tw93.github.io/assets/51521054/77ba3da3-114b-4e24-9ba9-3d0bfa00e4ac)

这是部署时候的一些相关参数配置：

![image](https://github.com/tw93/tw93.github.io/assets/51521054/585762f9-6e5f-4c26-ba1d-01e194d85789)

由于不是专业的开发人员，所以想请教下，如果我想部署到 Vercel 或者 Cloudflare Pages 上应该如何正确操作？

**Comment by tw93** [comment]
我的是这样的，也是用 vercel 部署的，你看看我的，不需要覆盖选中
<img width="1004" alt="image" src="https://github.com/tw93/tw93.github.io/assets/8736212/f845b1a9-24e1-4783-8660-09a344067862">
