### ISSUE TITLE
首页的post.title样式有点问题哈

### ISSUE THREAD

**Issue by yangchuang** [tw93/tw93.github.io#152]
如图：
<img width="1127" alt="image" src="https://github.com/tw93/tw93.github.io/assets/3096747/88e2f29e-8060-4a16-991a-35efc2538a1e">

**Comment by tw93** [comment]
谢谢反馈 看起来和屏幕适配有关系，8年前写的代码，哈哈，我去优化一下

**Comment by tw93** [comment]
修复了，哈哈，居然是svg的长度限制问题，改了改
