### ISSUE TITLE
大环境不好的情况下如何🐶着 - Tw93

### ISSUE THREAD

**Issue by tw93** [tw93/tw93.github.io#82]
https://tw93.fun/2022-07-01/gou.html 

 Hi，我是 Tw93，是一个前端工程师，空闲也折腾 iOS / macOS ，喜欢开源分享交流。Life大概是今年4月份的一个思考，来聊聊，作为一个国内开发工程师，如何在大环境不好的情况🐶着变强。

**Comment by Meeken1998** [comment]
真相了
